### ISSUE TITLE
[BUG] error while using action

### ISSUE THREAD

**Issue by Vodianoi** [GreenTF/upload-thunderstore-package#12]
Error: 'ghcr.io/greentf/utp:latest' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
https://github.com/Vodianoi/QuickPingMod/actions/runs/3906964669/jobs/6675678375

Is it supposed to be used in Docker environment ?

**Comment by AnActualEmerald** [comment]
Evidently I do need the `docker://` scheme in the image URL. For whatever reason it worked fine in my testing in this repo but breaks in other repos? Should have it fixed later tonight.

**Comment by AnActualEmerald** [comment]
should be fixed by #13
