### ISSUE TITLE
Action should strip leading `v` on from tag by default

### ISSUE THREAD

**Issue by GeckoEidechse** [GreenTF/upload-thunderstore-package#19]
The convention is to use a leading for version number tags, i.e. `git tag v4.2.0` However Thunderstore strictly requires a `X.Y.Z` version number format, i.e. no leading `v`.

As such the action should strip the leading `v` from the tag when generating the version number for Thunderstore.

Alternatively https://github.com/GreenTF/NSModTemplate could be updated to pass a stripped version number to the action instead of `github.ref_name` ^^

**Comment by AnActualEmerald** [comment]
This should be the case at the moment, is it not working that way?

**Comment by GeckoEidechse** [comment]
Nope, doing `git tag v0.0.5` I get:

![image](https://user-images.githubusercontent.com/40122905/234843569-dc7ae071-154e-40c6-a08d-8f6206bbb7ae.png)

https://github.com/GeckoEidechse/S_is_for_Stryder/actions/runs/4818960813/jobs/8581595797

**Comment by AnActualEmerald** [comment]
Okay, I found the issue 🫡
