### ISSUE TITLE
Unclear instruction for when category name contains space

### ISSUE THREAD

**Issue by GeckoEidechse** [GreenTF/upload-thunderstore-package#20]
The action uses spaces as a delimiter for defining multiple categories to upload a mod under, i.e. from the readme it says

> A list, separated by spaces of categories to give to the mod when published. These must be available in the community you're publishing to.

Thing is the Northstar community for example has multiple categories that have spaces in their name:

![image](https://user-images.githubusercontent.com/40122905/234731985-cee7f96d-15fc-44eb-bbb7-0e654e236453.png)

It's not clear how to escape the space in such a case or if it is even possible to upload to such a category using the action ^^

**Comment by AnActualEmerald** [comment]
I don't think this is actually possible with out `cfg_edit.js` handles the categories right now (woops)

I'll look into making that input accept a multiline string rather than a space delimited list

**Comment by GeckoEidechse** [comment]
I guess a list in YAML would be the cleanest option?

```yaml
categories:
  - "mods"
  - "Custom menu"
```

Regardless any solution will be breaking to current syntax so I guess we'll also need a version bump ^^

**Comment by AnActualEmerald** [comment]
I'm not sure if action inputs can be types other than strings, especially in this case since it gets stuffed into an environment variable. Alternatively it could just be comma delimited I think, I don't remember why I didn't do that in the first place (perhaps a holdover from trying to do all of it in bash)
