### ISSUE TITLE
Some help needed

### ISSUE THREAD

**Issue by jpw1991** [GreenTF/upload-thunderstore-package#23]
Hello,

I'm trying to get this to work for my stuff. It's failing on the publish phase. Here's my [failed job](https://github.com/jpw1991/chebs-necromancy/actions/runs/5292110893/jobs/9578576507).

My package looks like:

![image](https://github.com/GreenTF/upload-thunderstore-package/assets/13718599/c1f7c4f5-81c6-46f8-b3ce-207001862295)

And I just want to send the first zip to the Thunderstore.

**Comment by AnActualEmerald** [comment]
Try updating the action to `v4`, I think `v3.1` is broken now

**Comment by jpw1991** [comment]
Thanks for the suggestion. Same error with v4 unfortunately. Here's the [failed job](https://github.com/jpw1991/chebs-necromancy/actions/runs/5292479442/jobs/9579409723)

**Comment by AnActualEmerald** [comment]
Oh I see the issue, the `publish` job also needs `- uses: actions/checkout@v3` at the top

Also as it's set up right now, the entire contents of your repo will be uploaded to thunderstore which I don't think is what you're looking for?

**Comment by jpw1991** [comment]
I'd just like the first file of the Release to be put up. Can I use something like:

`file: ${{ github.event.release.assets[0] }}`?

**Comment by AnActualEmerald** [comment]
Oh, if only it were that easy 😅

I think adding a step like:

```bash 
wget https://github.com/jpw1991/chebs-necromancy/releases/download/${{ github.ref_name }}/ChebsNecromancy.${{ github.ref_name }}.zip```

To get the file then setting the `file` input like:

```yml
file: ChebsNecromancy.${{ github.ref_name }}.zip```

Should work

**Comment by jpw1991** [comment]
It works! Thanks so much
