### ISSUE TITLE
Question about `file`

### ISSUE THREAD

**Issue by NotNite** [GreenTF/upload-thunderstore-package#24]
Heya,

I'm planning to use this action to deploy [my mod](https://github.com/SlopCrew/SlopCrew) automatically. My CI setup already outputs .zip files ready to be uploaded to Thunderstore, which I wish to upload directly using `file`.

- Why is `description` required if it's specified in the manifest in the .zip?
- Will it read the `icon`/`readme`/`categories`/`deps`/`website` from the artifact I provide automatically? Do I need to provide these twice?

My understanding is that the action has an optional build step to create the .zip file, but I am unsure if it will properly read the existing contents of the zip file (like the Thunderstore website does).

Thanks!

**Comment by AnActualEmerald** [comment]
If you have a prebuilt file then you can just fill in all the required metadata fields with empty strings, basically the action naively sets up the project as if it was going to build it but then skips the actual build step when it gets to it. The manifest/icon/whatever else in the zip file you provide will be read by Thunderstone when it's uploaded, so you shouldn't need to provide any of those separately.
