### ISSUE TITLE
Support for setting website URL and auto-setting website URL to repo URL

### ISSUE THREAD

**Issue by GeckoEidechse** [GreenTF/upload-thunderstore-package#8]
The JSON manifest in Thunderstore allows setting a website URL. Usually this is just the URL to the GitHub repo that hosts the code of a certain mod.

```json
{
    "name": "My Awesome Mod",
    "description": "An awesome mod I made",
    "website_url": "https://github.com/example/test", // <--- this one
    "dependencies": [
        "Example-Mod-4.2.0"
    ],
    "version_number": "0.6.9"
}
```

It would be nice if the action would support setting a website URL. Further if no website URL is provided it should just default to the current repo URL, to require as little configuration from the modder as possible. ^^

**Comment by AnActualEmerald** [comment]
I had even considered doing this but just didn't idk. `website` should default to the repo URL now :)

**Comment by GeckoEidechse** [comment]
That was quick ^^
